# this class include all the labels in the image dataset 
# but we only need 8 of them as our training target
class Label:
    img_labels = ['Speed_limit_5',
    'Speed_limit_15',
    'Speed_limit_30',
    'Speed_limit_40',
    'Speed_limit_50',
    'Speed_limit_60',
    'Speed_limit_70',
    'Speed_limit_80',
    'No straight or right turn',
    'No straight or left turn',
    'No straight',
    'No left turn',
    'Do not turn left and right',
    'No right turn',
    'No Overhead',
    'No U-turn',
    'No Motor vehicle',
    'No whistle',
    'Unrestricted speed_40',
    'Unrestricted speed_50',
    'Straight or turn right',
    'Straight',
    'Turn left',
    'Turn left or turn right',
    'Turn right',
    'Drive on the left side of the road',
    'Drive on the right side of the road',
    'Driving around the island',
    'Motor vehicle driving',
    'Whistle',
    'Non-motorized',
    'U-turn',
    'Left-right detour',
    'traffic light',
    'Drive cautiously',
    'Caution Pedestrians',
    'Attention non-motor vehicle',
    'Mind the children',
    'Sharp turn to the right',
    'Sharp turn to the left',
    'Downhill steep slope',
    'Uphill steep slope',
    'Go slow',
    'Right T-shaped cross',
    'Left T-shaped cross',
    'village',
    'Reverse detour',
    'Railway crossing-1',
    'construction',
    'Continuous detour',
    'Railway crossing-2',
    'Accident-prone road section',
    'stop',
    'No passing',
    'No Parking',
    'No entry',
    'Deceleration and concession',
    'Stop For Check',
    'Background']
    target=[0,1,2,6,img_labels.index('Straight'),img_labels.index('Turn right'),img_labels.index('Turn left'),img_labels.index('Go slow'),
           img_labels.index('stop')]