data:
  doc_size: 10
  history_size: 50
  word_size: 30004
  entity_size: 17043
  data_format: dkn
  
info:
  metrics:
  - auc
  pairwise_metrics:
  - mean_mrr
  - ndcg@5;10
  show_step: 10000
  
model:
  method : classification
  activation:
  - sigmoid
  attention_activation: relu
  attention_dropout: 0.0
  attention_layer_sizes: 100
  dim: 100
  use_entity: true
  use_context: false
 
  entity_dim: 100
  entity_embedding_method: TransE
  transform: true
 
  dropout:
  - 0.0
  filter_sizes:
  - 1
  - 2
  - 3
  layer_sizes:
  - 300
  # model_type: DKN_without_context
  model_type: dkn
  num_filters: 100
  infer_model_name : epoch_2

train:
  batch_size: 100
  embed_l1: 0.000
  embed_l2: 0.000
  epochs: 10
  init_method: xavier_normal
  init_value: 0.1
  layer_l1: 0.000
  layer_l2: 0.000001
  learning_rate: 0.0003
  loss: log_loss
  is_clip_norm: False
  max_grad_norm: 0.2
  optimizer: adam
  save_model: False
  save_epoch : 2
  enable_BN : True
